-- AlterTable
ALTER TABLE `pro_produto` MODIFY `pro_tipo` ENUM('SUSPENSAO', 'FREIO', 'MOTOR', 'TRANSMISSAO', 'ELETRICA', 'LATARIA', 'ACESSORIOS') NOT NULL DEFAULT 'ACESSORIOS',
    MODIFY `pro_status` BOOLEAN NOT NULL DEFAULT true,
    MODIFY `pro_validade` DATETIME(3) NULL;
